package com.example.ui

object Localizer {
    
    private val translations = mapOf(
        "app_title" to mapOf("TR" to "MARGIN CALL","EN" to "MARGIN CALL","HI" to "MARGIN CALL","ZH" to "MARGIN CALL","FR" to "MARGIN CALL","RU" to "MARGIN CALL","AZ" to "MARGIN CALL"),
        "google_login_title" to mapOf("TR" to "Borsaya Giriş Yap","EN" to "Log in to Exchange","HI" to "एक्सचेंज में लॉगिन करें","ZH" to "登录交易系统","FR" to "Se Connecter à l'Échange","RU" to "Вход на биржу","AZ" to "Birjaya Giriş Et"),
        "login_btn" to mapOf("TR" to "Giriş Yap","EN" to "Login","HI" to "लॉग इन","ZH" to "登录","FR" to "Connexion","RU" to "Войти","AZ" to "Giriş Et"),
        "register_btn" to mapOf("TR" to "Hesap Oluştur","EN" to "Create Account","HI" to "खाता बनाएं","ZH" to "注册账户","FR" to "Créer un compte","RU" to "Создать аккаунт","AZ" to "Hesab Yarat"),
        "login_title" to mapOf("TR" to "Giriş Yap","EN" to "Sign In","HI" to "साइन इन करें","ZH" to "登录","FR" to "Se connecter","RU" to "Войти","AZ" to "Daxil ol"),
        "register_title" to mapOf("TR" to "Yeni Hesap Oluştur","EN" to "Create New Account","HI" to "नया खाता बनाएं","ZH" to "创建新账户","FR" to "Créer un nouveau compte","RU" to "Создать новый аккаунт","AZ" to "Yeni Hesab Yarat"),
        "username" to mapOf("TR" to "Kullanıcı Adı","EN" to "Username","HI" to "उपयोगकर्ता नाम","ZH" to "用户名","FR" to "Nom d'utilisateur","RU" to "Имя пользователя","AZ" to "İstifadəçi adı"),
        "password" to mapOf("TR" to "Şifre","EN" to "Password","HI" to "पासवर्ड","ZH" to "密码","FR" to "Mot de passe","RU" to "Пароль","AZ" to "Şifrə"),
        "confirm_password" to mapOf("TR" to "Şifre Tekrarı","EN" to "Confirm Password","HI" to "पासवर्ड की पुष्टि","ZH" to "确认密码","FR" to "Confirmer le mot de passe","RU" to "Подтвердите пароль","AZ" to "Şifrəni təsdiqlə"),
        "display_name" to mapOf("TR" to "Görünen Ad (İsteğe Bağlı)","EN" to "Display Name (Optional)","HI" to "प्रदर्शन नाम (वैकल्पिक)","ZH" to "显示名称（可选）","FR" to "Nom affiché (optionnel)","RU" to "Отображаемое имя (необязательно)","AZ" to "Görünən ad (isteğe bağlı)"),
        "max_accounts_info" to mapOf("TR" to "Bu cihazda maksimum 2 hesap açılabilir.","EN" to "Maximum 2 accounts per device.","HI" to "प्रति डिवाइस अधिकतम 2 खाते।","ZH" to "每台设备最多2个账户。","FR" to "Maximum 2 comptes par appareil.","RU" to "Максимум 2 аккаунта на устройство.","AZ" to "Cihaz başına maksimum 2 hesab."),
        "accounts_on_device" to mapOf("TR" to "hesap bu cihazda","EN" to "accounts on this device","HI" to "इस डिवाइस पर खाते","ZH" to "个账户在此设备","FR" to "comptes sur cet appareil","RU" to "аккаунтов на устройстве","AZ" to "hesab bu cihazda"),
        "back" to mapOf("TR" to "Geri","EN" to "Back","HI" to "वापस","ZH" to "返回","FR" to "Retour","RU" to "Назад","AZ" to "Geri"),
        "cancel" to mapOf("TR" to "Vazgeç","EN" to "Cancel","HI" to "रद्द करें","ZH" to "取消","FR" to "Annuler","RU" to "Отмена","AZ" to "Ləğv et"),
        "portfolio" to mapOf("TR" to "Portföy","EN" to "Portfolio","HI" to "पोर्टफोलियो","ZH" to "投资组合","FR" to "Portefeuille","RU" to "Портфель","AZ" to "Portfel"),
        "market" to mapOf("TR" to "Grafik","EN" to "Charts","HI" to "चार्ट","ZH" to "图表","FR" to "Graphiques","RU" to "Графики","AZ" to "Qrafiklər"),
        "social_feed" to mapOf("TR" to "Akış","EN" to "Feed","HI" to "फ़ीड","ZH" to "动态","FR" to "Flux","RU" to "Лента","AZ" to "Axın"),
        "leaderboard" to mapOf("TR" to "Sıralama","EN" to "Rankings","HI" to "रैंकिंग","ZH" to "排行榜","FR" to "Classement","RU" to "Рейтинги","AZ" to "Sıralama"),
        "mini_games" to mapOf("TR" to "Yaşam & İş","EN" to "Life & Jobs","HI" to "जीवन और काम","ZH" to "生活与工作","FR" to "Vie & Emplois","RU" to "Жизнь и работа","AZ" to "Həyat və İş"),
        "earn_capital_desc" to mapOf("TR" to "Sermayeniz sıfır! Mini oyunları oynayarak ilk fonlarınızı kazanın.","EN" to "Your capital is zero! Play mini-games to earn your initial funds.","HI" to "आपकी पूंजी शून्य है! मिनी-गेम खेलें।","ZH" to "您的资本为零！通过玩小游戏来赚取资金。","FR" to "Votre capital est à zéro ! Jouez à des mini-jeux.","RU" to "Ваш капитал равен нулю! Играйте в мини-игры.","AZ" to "Sermayəniz sıfırdır! Mini oyunlar oynayın."),
        "available_cash" to mapOf("TR" to "Kullanılabilir Nakit","EN" to "Available Cash","HI" to "उपलब्ध नकद","ZH" to "可用现金","FR" to "Espèces Disponibles","RU" to "Доступные наличные","AZ" to "Mövcud Nağd Pul"),
        "total_equity" to mapOf("TR" to "Toplam Varlık Değeri","EN" to "Total Net Worth","HI" to "कुल शुद्ध मूल्य","ZH" to "总净资产","FR" to "Valeur Nette Totale","RU" to "Общая стоимость активов","AZ" to "Ümumi Aktiv Dəyəri"),
        "spot_trade" to mapOf("TR" to "Spot İşlem","EN" to "Spot Trading","HI" to "स्पॉट ट्रेडिंग","ZH" to "现货交易","FR" to "Trading Spot","RU" to "Спот торговля","AZ" to "Spot Ticarət"),
        "leverage_trade" to mapOf("TR" to "Kaldıraçlı İşlem","EN" to "Leverage (Futures)","HI" to "लेवरेज ट्रेडिंग","ZH" to "杠杆(合约)","FR" to "Marge & Levier","RU" to "Маржинальная торговля","AZ" to "Kaldıraçlı Ticarət"),
        "buy" to mapOf("TR" to "AL","EN" to "BUY","HI" to "खरीदें","ZH" to "买入","FR" to "ACHETER","RU" to "КУПИТЬ","AZ" to "AL"),
        "sell" to mapOf("TR" to "SAT","EN" to "SELL","HI" to "बेचें","ZH" to "卖出","FR" to "VENDRE","RU" to "ПРОДАТЬ","AZ" to "SAT"),
        "long" to mapOf("TR" to "LONG (YÜKSELİŞ)","EN" to "LONG (BUY)","HI" to "लॉन्ग (खरीदें)","ZH" to "看涨 (LONG)","FR" to "LONG (ACHAT)","RU" to "LONG (ПОКУПКА)","AZ" to "LONG (YÜKSƏLİŞ)"),
        "short" to mapOf("TR" to "SHORT (DÜŞÜŞ)","EN" to "SHORT (SELL)","HI" to "शॉर्ट (बेचें)","ZH" to "看跌 (SHORT)","FR" to "SHORT (VENTE)","RU" to "SHORT (ПРОДАЖА)","AZ" to "SHORT (DÜŞÜŞ)"),
        "leverage" to mapOf("TR" to "Kaldıraç","EN" to "Leverage","HI" to "लेवरेज","ZH" to "杠杆","FR" to "Levier","RU" to "Кредитное плечо","AZ" to "Kaldıraç"),
        "margin" to mapOf("TR" to "Teminat Miktarı","EN" to "Margin Amount","HI" to "मार्जिन राशि","ZH" to "保证金数额","FR" to "Montant de la Marge","RU" to "Сумма маржи","AZ" to "Girov Miqdarı"),
        "take_profit" to mapOf("TR" to "Kâr Al (%)","EN" to "Take Profit (%)","HI" to "लाभ लें (%)","ZH" to "止盈 (%)","FR" to "Prendre les Profits (%)","RU" to "Тейк-Профит (%)","AZ" to "Qazanc Al (%)"),
        "stop_loss" to mapOf("TR" to "Zarar Kes (%)","EN" to "Stop Loss (%)","HI" to "स्टॉप लॉस (%)","ZH" to "止损 (%)","FR" to "Stop Loss (%)","RU" to "Стоп-Лосс (%)","AZ" to "Zərəri Kəs (%)"),
        "open_position" to mapOf("TR" to "POZİSYON AÇ","EN" to "OPEN POSITION","HI" to "पोजीशन खोलें","ZH" to "开仓","FR" to "OUVRIR UNE POSITION","RU" to "ОТКРЫТЬ ПОЗИЦИЮ","AZ" to "POZİSİYA AÇ"),
        "positions" to mapOf("TR" to "Açık Pozisyonlar","EN" to "Open Positions","HI" to "खुली पोजीशन","ZH" to "持仓","FR" to "Positions Ouvertes","RU" to "Открытые позиции","AZ" to "Açıq Mövqelər"),
        "close" to mapOf("TR" to "Kapat","EN" to "Close","HI" to "बंद करें","ZH" to "关闭","FR" to "Fermer","RU" to "Закрыть","AZ" to "Bağla"),
        "settings" to mapOf("TR" to "Ayarlar","EN" to "Settings","HI" to "सेटिंग्स","ZH" to "设置","FR" to "Paramètres","RU" to "Настройки","AZ" to "Parametrlər"),
        "language" to mapOf("TR" to "Dil Seçimi","EN" to "Language","HI" to "भाषा","ZH" to "语言","FR" to "Langue","RU" to "Язык","AZ" to "Dil"),
        "market_speed" to mapOf("TR" to "Piyasa Hızı","EN" to "Market Speed","HI" to "बाज़ार की गति","ZH" to "市场速度","FR" to "Vitesse du Marché","RU" to "Скорость рынка","AZ" to "Bazar Sürəti"),
        "speed_slow" to mapOf("TR" to "Yavaş","EN" to "Slow","HI" to "धीमा","ZH" to "慢","FR" to "Lent","RU" to "Медленно","AZ" to "Yavaş"),
        "speed_normal" to mapOf("TR" to "Normal","EN" to "Normal","HI" to "सामान्य","ZH" to "正常","FR" to "Normal","RU" to "Нормально","AZ" to "Normal"),
        "speed_fast" to mapOf("TR" to "Hızlı","EN" to "Fast","HI" to "तेज़","ZH" to "快","FR" to "Rapide","RU" to "Быстро","AZ" to "Sürətli"),
        "speed_turbo" to mapOf("TR" to "Turbo","EN" to "Turbo","HI" to "टर्बो","ZH" to "极速","FR" to "Turbo","RU" to "Турбо","AZ" to "Turbo"),
        "reset_game" to mapOf("TR" to "Oyunu Sıfırla","EN" to "Reset Game","HI" to "गेम रीसेट करें","ZH" to "重置游戏","FR" to "Réinitialiser le jeu","RU" to "Сбросить игру","AZ" to "Oyunu Sıfırla"),
        "reset_game_desc" to mapOf("TR" to "Oyunu sıfırladığınızda tüm ilerlemeniz silinir, $0 bakiye ile intro animasyonundan yeniden başlarsınız.","EN" to "Resetting erases all progress. You restart from the intro animation with $0 balance.","HI" to "रीसेट करने से सभी प्रगति मिट जाती है। आप $0 के साथ फिर से शुरू होते हैं।","ZH" to "重置将清除所有进度，从头开始以$0余额重新开始。","FR" to "La réinitialisation efface toute la progression. Vous recommencez avec $0.","RU" to "Сброс удалит весь прогресс. Вы начнёте заново с $0.","AZ" to "Sıfırlama bütün irəliləyişi silir. $0 balansı ilə yenidən başlayırsınız."),
        "reset_game_btn" to mapOf("TR" to "OYUNU SIFIRLA","EN" to "RESET GAME","HI" to "गेम रीसेट करें","ZH" to "重置游戏","FR" to "RÉINITIALISER","RU" to "СБРОСИТЬ ИГРУ","AZ" to "OYUNU SIFIRLA"),
        "reset_confirm_title" to mapOf("TR" to "Emin misiniz?","EN" to "Are you sure?","HI" to "क्या आप सुनिश्चित हैं?","ZH" to "您确定吗？","FR" to "Êtes-vous sûr ?","RU" to "Вы уверены?","AZ" to "Əminsiniz?"),
        "reset_confirm_desc" to mapOf("TR" to "Tüm ilerlemeniz, para ve varlıklarınız silinecek. Bu işlem geri alınamaz!","EN" to "All your progress, money and assets will be deleted. This cannot be undone!","HI" to "आपकी सभी प्रगति, पैसा और संपत्ति हटा दी जाएगी। यह पूर्ववत नहीं किया जा सकता!","ZH" to "您所有的进度、金钱和资产都将被删除。此操作无法撤消！","FR" to "Toute votre progression, argent et actifs seront supprimés. Impossible à annuler !","RU" to "Весь ваш прогресс, деньги и активы будут удалены. Это невозможно отменить!","AZ" to "Bütün irəliləyişiniz, pul və aktivləriniz silinəcək. Bu geri qaytarıla bilməz!"),
        "reset_confirm_btn" to mapOf("TR" to "Evet, Sıfırla","EN" to "Yes, Reset","HI" to "हाँ, रीसेट करें","ZH" to "是的，重置","FR" to "Oui, réinitialiser","RU" to "Да, сбросить","AZ" to "Bəli, Sıfırla"),
        "about" to mapOf("TR" to "Hakkında","EN" to "About","HI" to "के बारे में","ZH" to "关于","FR" to "À propos","RU" to "О приложении","AZ" to "Haqqında"),
        "about_desc" to mapOf("TR" to "Gerçek piyasa dinamikleri ile borsa simülasyonu. PROTRADER698 yapımı.","EN" to "Stock market simulation with real market dynamics. By PROTRADER698.","HI" to "वास्तविक बाज़ार गतिशीलता के साथ शेयर बाज़ार सिमुलेशन।","ZH" to "具有真实市场动态的股市模拟。","FR" to "Simulation boursière avec des dynamiques de marché réelles.","RU" to "Симуляция фондового рынка с реальной динамикой.","AZ" to "Real bazar dinamikası ilə fond birjası simulyasiyası."),
        "news" to mapOf("TR" to "Haberler","EN" to "News","HI" to "समाचार","ZH" to "新闻","FR" to "Actualités","RU" to "Новости","AZ" to "Xəbərlər"),
        "life_simulator" to mapOf("TR" to "YAŞAM & İŞ SİMÜLATÖRÜ","EN" to "LIFE & JOB SIMULATOR","HI" to "जीवन और काम सिमुलेटर","ZH" to "生活与工作模拟器","FR" to "SIMULATEUR DE VIE & EMPLOI","RU" to "СИМУЛЯТОР ЖИЗНИ И РАБОТЫ","AZ" to "HƏYAT VƏ İŞ SİMULYATORU"),
        "jobs_tab" to mapOf("TR" to "İşler","EN" to "Jobs","HI" to "नौकरियाँ","ZH" to "工作","FR" to "Emplois","RU" to "Работа","AZ" to "İşlər"),
        "my_house_tab" to mapOf("TR" to "Evim","EN" to "My House","HI" to "मेरा घर","ZH" to "我的房子","FR" to "Ma Maison","RU" to "Мой дом","AZ" to "Evim"),
        "garage_tab" to mapOf("TR" to "Garaj","EN" to "Garage","HI" to "गैराज","ZH" to "车库","FR" to "Garage","RU" to "Гараж","AZ" to "Qaraj"),
        "properties_tab" to mapOf("TR" to "Mülkler","EN" to "Properties","HI" to "संपत्तियां","ZH" to "房产","FR" to "Propriétés","RU" to "Недвижимость","AZ" to "Əmlaklar"),
        "inventory_tab" to mapOf("TR" to "Envanter","EN" to "Inventory","HI" to "इन्वेंटरी","ZH" to "库存","FR" to "Inventaire","RU" to "Инвентарь","AZ" to "İnventar"),
        "buy_property" to mapOf("TR" to "Satın Al","EN" to "Buy","HI" to "खरीदें","ZH" to "购买","FR" to "Acheter","RU" to "Купить","AZ" to "Satın Al"),
        "sell" to mapOf("TR" to "Sat","EN" to "Sell","HI" to "बेचें","ZH" to "卖出","FR" to "Vendre","RU" to "Продать","AZ" to "Sat"),
        "list_for_sale" to mapOf("TR" to "Satışa Koy","EN" to "List for Sale","HI" to "बिक्री के लिए सूचीबद्ध करें","ZH" to "挂牌出售","FR" to "Mettre en vente","RU" to "Выставить на продажу","AZ" to "Satışa Çıxar"),
        "cancel_listing" to mapOf("TR" to "İlanı Geri Al","EN" to "Cancel Listing","HI" to "लिस्टिंग रद्द करें","ZH" to "取消挂牌","FR" to "Annuler l'annonce","RU" to "Отменить объявление","AZ" to "Elanı Ləğv et"),
        "listing_price" to mapOf("TR" to "Satış Fiyatı","EN" to "Listing Price","HI" to "लिस्टिंग मूल्य","ZH" to "挂牌价格","FR" to "Prix de vente","RU" to "Цена продажи","AZ" to "Satış Qiyməti"),
        "market_value" to mapOf("TR" to "Piyasa Değeri","EN" to "Market Value","HI" to "बाज़ार मूल्य","ZH" to "市场价值","FR" to "Valeur marchande","RU" to "Рыночная стоимость","AZ" to "Bazar Dəyəri"),
        "owned" to mapOf("TR" to "Sahip Olduğunuz","EN" to "Owned","HI" to "आपके पास","ZH" to "拥有","FR" to "Possédé","RU" to "Ваше имущество","AZ" to "Sahibsiniz"),
        "for_sale" to mapOf("TR" to "Satışta","EN" to "For Sale","HI" to "बिक्री के लिए","ZH" to "待售","FR" to "À vendre","RU" to "На продаже","AZ" to "Satışda"),
        "drive" to mapOf("TR" to "3D ŞEHIRDE SÜR","EN" to "DRIVE IN 3D CITY","HI" to "3D शहर में ड्राइव करें","ZH" to "在3D城市驾驶","FR" to "CONDUIRE EN VILLE 3D","RU" to "ЕХАТЬ В 3D ГОРОДЕ","AZ" to "3D ŞƏHƏRDƏ SÜR"),
        "no_car" to mapOf("TR" to "Henüz arabanız yok! Garaj bölümünden bir araba satın alın.","EN" to "No car yet! Buy one from the Garage section.","HI" to "अभी कोई कार नहीं! गैराज सेक्शन से खरीदें।","ZH" to "还没有车！从车库部分购买。","FR" to "Pas de voiture ! Achetez-en une dans la section Garage.","RU" to "Нет автомобиля! Купите его в разделе Гараж.","AZ" to "Hələ avtomobil yoxdur! Qaraj bölməsindən alın."),
        "select_car" to mapOf("TR" to "Araba Seç","EN" to "Select Car","HI" to "कार चुनें","ZH" to "选择汽车","FR" to "Choisir une voiture","RU" to "Выбрать автомобиль","AZ" to "Avtomobil Seç"),
        "active_car" to mapOf("TR" to "Aktif Araç","EN" to "Active Car","HI" to "सक्रिय कार","ZH" to "当前汽车","FR" to "Voiture active","RU" to "Активный автомобиль","AZ" to "Aktiv Avtomobil"),
        "sell_car" to mapOf("TR" to "Arabayı Sat","EN" to "Sell Car","HI" to "कार बेचें","ZH" to "卖车","FR" to "Vendre la voiture","RU" to "Продать автомобиль","AZ" to "Avtomobili Sat"),
        "sell_furniture" to mapOf("TR" to "Eşyayı Sat","EN" to "Sell Item","HI" to "वस्तु बेचें","ZH" to "出售物品","FR" to "Vendre l'article","RU" to "Продать предмет","AZ" to "Əşyanı Sat"),
        "my_inventory" to mapOf("TR" to "Envanterim","EN" to "My Inventory","HI" to "मेरी इन्वेंटरी","ZH" to "我的库存","FR" to "Mon inventaire","RU" to "Мой инвентарь","AZ" to "Mənim Inventarım"),
        "waiter_job" to mapOf("TR" to "Garsonluk","EN" to "Waitering","HI" to "वेटिंग","ZH" to "服务员","FR" to "Service en salle","RU" to "Официант","AZ" to "Ofisiant"),
        "electrician_job" to mapOf("TR" to "Elektrikçilik","EN" to "Electrician","HI" to "इलेक्ट्रीशियन","ZH" to "电工","FR" to "Électricien","RU" to "Электрик","AZ" to "Elektrikçi"),
        "mining_job" to mapOf("TR" to "Kaya Kırma","EN" to "Stone Mining","HI" to "पत्थर खनन","ZH" to "采石","FR" to "Extraction de pierre","RU" to "Добыча камня","AZ" to "Daş Qazıma"),
        "no_money" to mapOf("TR" to "Yetersiz nakit!","EN" to "Insufficient funds!","HI" to "अपर्याप्त धन!","ZH" to "资金不足！","FR" to "Fonds insuffisants !","RU" to "Недостаточно средств!","AZ" to "Kifayət qədər nağd pul yoxdur!"),
        "cash" to mapOf("TR" to "Nakit","EN" to "Cash","HI" to "नकद","ZH" to "现金","FR" to "Argent","RU" to "Наличные","AZ" to "Nağd pul"),
        "day" to mapOf("TR" to "Gün","EN" to "Day","HI" to "दिन","ZH" to "天","FR" to "Jour","RU" to "День","AZ" to "Gün"),
        "month" to mapOf("TR" to "Ay","EN" to "Month","HI" to "महीना","ZH" to "月","FR" to "Mois","RU" to "Месяц","AZ" to "Ay"),
        "bankruptcy_warning_1" to mapOf("TR" to "⚠️ DİKKAT: Bakiyeniz -$1000'a düştü! İflas eşiğine yaklaşıyorsunuz!","EN" to "⚠️ WARNING: Balance dropped to -$1000! Approaching bankruptcy!","HI" to "⚠️ चेतावनी: बैलेंस -$1000 पर आ गया!","ZH" to "⚠️ 警告：余额降至-$1000！","FR" to "⚠️ ATTENTION: Solde à -$1000!","RU" to "⚠️ ВНИМАНИЕ: Баланс -$1000!","AZ" to "⚠️ DİQQƏT: Balans -$1000'a düşdü!"),
        "bankruptcy_warning_2" to mapOf("TR" to "🚨 ACİL: Bakiyeniz -$2000! İFLAS SINIRI -$3000!","EN" to "🚨 CRITICAL: Balance -$2000! BANKRUPTCY AT -$3000!","HI" to "🚨 गंभीर: बैलेंस -$2000!","ZH" to "🚨 紧急：余额-$2000！破产线-$3000！","FR" to "🚨 CRITIQUE: Solde -$2000!","RU" to "🚨 КРИТИЧНО: Баланс -$2000!","AZ" to "🚨 TƏCİLİ: Balans -$2000!")
    )

    fun translate(key: String, lang: String): String {
        return translations[key]?.get(lang)
            ?: translations[key]?.get("EN")
            ?: key
    }
}
